#!/usr/bin/env python3
"""
Telegram Alert Workflow Test

This script tests the complete Telegram alert workflow from trigger to delivery.
It simulates the analysis engine workflow and sends a test alert.

Usage:
    python tests/test_telegram_alert_workflow.py
"""

import os
import sys
from datetime import datetime, timedelta, timezone
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Import after loading env
from src.database.models import Match, SessionLocal, init_db
from src.alerting.notifier import send_alert, validate_telegram_credentials, validate_telegram_chat_id

def create_test_match():
    """Create a test match object for testing alerts."""
    # Create a mock match object
    class TestMatch:
        def __init__(self):
            self.id = 999999
            self.home_team = "Test Home"
            self.away_team = "Test Away"
            self.league = "Test League"
            self.start_time = datetime.now(timezone.utc) + timedelta(hours=2)
            self.opening_home_odd = 2.50
            self.current_home_odd = 2.10  # 16% drop - should trigger alert
            self.opening_away_odd = 3.00
            self.current_away_odd = 3.00
            self.opening_draw_odd = 3.20
            self.current_draw_odd = 3.20
            self.current_over_2_5 = 1.85
            self.current_under_2_5 = 2.00
    
    return TestMatch()

def test_telegram_workflow():
    """Test the complete Telegram alert workflow."""
    print("=" * 70)
    print("🧪 TELEGRAM ALERT WORKFLOW TEST")
    print("=" * 70)
    
    # Step 1: Validate Telegram credentials
    print("\n[1/5] 🔍 Validating Telegram credentials...")
    try:
        if validate_telegram_credentials():
            print("   ✅ Telegram credentials validated successfully")
        else:
            print("   ❌ Telegram credentials validation failed")
            return False
    except ValueError as e:
        print(f"   ❌ Telegram credentials error: {e}")
        return False
    except Exception as e:
        print(f"   ⚠️  Telegram validation skipped: {e}")
    
    # Step 2: Validate chat ID
    print("\n[2/5] 🔍 Validating Telegram chat ID...")
    if validate_telegram_chat_id():
        print("   ✅ Chat ID format is valid")
    else:
        print("   ❌ Chat ID format is invalid")
        return False
    
    # Step 3: Create test match
    print("\n[3/5] 🏟 Creating test match...")
    match = create_test_match()
    print(f"   ✅ Test match created: {match.home_team} vs {match.away_team}")
    print(f"   📊 Odds: {match.opening_home_odd:.2f} → {match.current_home_odd:.2f}")
    
    # Step 4: Check environment variables
    print("\n[4/5] 🔍 Checking environment configuration...")
    token = os.getenv("TELEGRAM_TOKEN") or os.getenv("TELEGRAM_BOT_TOKEN")
    chat_id = os.getenv("TELEGRAM_CHAT_ID")
    
    if token:
        print(f"   ✅ TELEGRAM_TOKEN: {token[:10]}...{token[-5:]}")
    else:
        print("   ❌ TELEGRAM_TOKEN not configured")
        return False
    
    if chat_id:
        print(f"   ✅ TELEGRAM_CHAT_ID: {chat_id}")
    else:
        print("   ❌ TELEGRAM_CHAT_ID not configured")
        return False
    
    # Step 5: Send test alert
    print("\n[5/5] 📤 Sending test alert to Telegram...")
    try:
        send_alert(
            match_obj=match,
            news_summary="Test alert for workflow verification. This is a simulated news summary that would normally be generated by the AI analysis engine.",
            news_url="https://example.com/test",
            score=9.5,  # High score to meet threshold
            league=match.league,
            combo_suggestion="Home Win",
            combo_reasoning="Test reasoning for combo suggestion",
            recommended_market="Home Win",
            math_edge={"market": "home_win", "edge": 15.0, "kelly_stake": 2.5},
            is_update=False,
            financial_risk=None,
            intel_source="test",
            referee_intel=None,
            twitter_intel=None,
            validated_home_team=None,
            validated_away_team=None,
            verification_info=None,
            final_verification_info=None,
            injury_intel=None,
            confidence_breakdown=None,
            is_convergent=False,
            convergence_sources=None,
        )
        print("   ✅ Test alert sent successfully!")
        print("\n" + "=" * 70)
        print("✅ TELEGRAM ALERT WORKFLOW TEST PASSED")
        print("=" * 70)
        print("\n💡 If you received the alert on Telegram, the workflow is working correctly.")
        print("💡 If you did NOT receive the alert, check:")
        print("   1. Your Telegram app notifications are enabled")
        print("   2. The bot is not blocked by you")
        print("   3. You have started a conversation with the bot (/start)")
        return True
    except Exception as e:
        print(f"   ❌ Failed to send test alert: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    success = test_telegram_workflow()
    sys.exit(0 if success else 1)
