"""
Team & League Name to FotMob ID Mapping

This file maps team names and league keys from The-Odds-API to FotMob IDs.
Auto-generated by mapping_tool.py

To find more FotMob IDs:
1. Run: python mapping_tool.py
2. Or visit fotmob.com and check team/league URLs
"""

# ============================================
# LEAGUE MAPPING (OddsAPI Key -> FotMob League ID)
# ============================================
# Critical for Motivation Engine V4.0 - League Table Context
LEAGUE_FOTMOB_IDS = {
    # Elite 6 Leagues
    "soccer_turkey_super_league": 71,
    "soccer_greece_super_league": 47,
    "soccer_spl": 50,  # Scotland Premiership
    "soccer_australia_aleague": 268,
    "soccer_argentina_primera_division": 112,
    "soccer_mexico_ligamx": 230,
    
    # Tier 2 Leagues
    "soccer_brazil_serie_b": 325,
    "soccer_poland_ekstraklasa": 196,
    "soccer_china_superleague": 182,
    "soccer_japan_j_league": 183,
    "soccer_korea_kleague1": 186,
    "soccer_saudi_professional_league": 278,
    
    # European Leagues (for future expansion)
    "soccer_epl": 47,  # England Premier League
    "soccer_spain_la_liga": 87,
    "soccer_germany_bundesliga": 54,
    "soccer_italy_serie_a": 55,
    "soccer_france_ligue_one": 53,
    "soccer_netherlands_eredivisie": 57,
    "soccer_portugal_primeira_liga": 61,
    "soccer_belgium_first_div": 114,
    "soccer_austria_bundesliga": 45,
    "soccer_switzerland_superleague": 215,
    "soccer_norway_eliteserien": 59,
    "soccer_sweden_allsvenskan": 67,
    "soccer_denmark_superliga": 48,
}


def get_fotmob_league_id(odds_api_key: str) -> int:
    """
    Get FotMob league ID from OddsAPI league key.
    
    Args:
        odds_api_key: League key from The-Odds-API (e.g., 'soccer_turkey_super_league')
        
    Returns:
        FotMob league ID or None if not mapped
    """
    return LEAGUE_FOTMOB_IDS.get(odds_api_key)


# ============================================
# TEAM MAPPING (The-Odds-API name -> FotMob ID)
# ============================================
TEAM_FOTMOB_IDS = {
    # Turkey Super Lig
    "Besiktas JK": 8598,
    "Galatasaray": 8601,
    "Fenerbahce": 8600,
    "Trabzonspor": 8609,
    
    # Poland Ekstraklasa
    "Legia Warsaw": 8673,
    "Lech Poznan": 8672,
    
    # Add more teams as needed via mapping_tool.py
}


def get_fotmob_team_id(team_name: str) -> int:
    """
    Get FotMob team ID from team name.
    
    Args:
        team_name: Team name from The-Odds-API
        
    Returns:
        FotMob team ID or None if not found
    """
    # Direct lookup
    if team_name in TEAM_FOTMOB_IDS:
        return TEAM_FOTMOB_IDS[team_name]
    
    # Try case-insensitive lookup
    team_lower = team_name.lower()
    for name, team_id in TEAM_FOTMOB_IDS.items():
        if name.lower() == team_lower:
            return team_id
    
    return None


def add_team_mapping(team_name: str, fotmob_id: int):
    """Add a new team mapping (runtime only)."""
    TEAM_FOTMOB_IDS[team_name] = fotmob_id



